//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika321App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academics
    {
        public int ID { get; set; }
        public string LName { get; set; }
        public string Fname { get; set; }
        public string SurName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> Year_Of_Getting_Rank { get; set; }
        public string Password { get; set; }
    }
}
