//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika321App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public string Number { get; set; }
        public int ID { get; set; }
        public string Id_Bid { get; set; }
    
        public virtual Disciple Disciple { get; set; }
        public virtual Specialization Specialization { get; set; }
    }
}
