//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika321App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class praktika_321Entities : DbContext
    {
        public praktika_321Entities()
            : base("name=praktika_321Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academics> Academics { get; set; }
        public virtual DbSet<Bid> Bid { get; set; }
        public virtual DbSet<cathedra> cathedra { get; set; }
        public virtual DbSet<Cathedra_Manager> Cathedra_Manager { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Disciple> Disciple { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Engeneer> Engeneer { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<faculty> faculty { get; set; }
        public virtual DbSet<Specialization> Specialization { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Ученики> Ученики { get; set; }
    }
}
