//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika321App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Disciple { get; set; }
        public Nullable<int> Reg_Number { get; set; }
        public Nullable<int> Teacher { get; set; }
        public string Room { get; set; }
        public Nullable<int> Grade { get; set; }
        public int ID_Exam { get; set; }
    
        public virtual Disciple Disciple1 { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher1 { get; set; }
    }
}
